import type { Metadata } from 'next';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { CssBaseline } from '@mui/material';
import ReactQueryProvider from '@/providers/ReactQueryProvider';
import App from '@/app/App';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};


export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang='en'>
        <body style={{ minHeight: '100vh', display: 'flex', flexDirection: 'column' }}>
        <CssBaseline/>
        <ReactQueryProvider>
            <AppRouterCacheProvider>
                <App>
                    {children}
                </App>
            </AppRouterCacheProvider>
        </ReactQueryProvider>
        </body>
        </html>
    );
}
