name: Deploy Web to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Copy prisma to web app
        run: cp -r prisma apps/web

      - name: Install dependencies (web)
        run: |
          cd apps/web
          npm install

      - name: Create prisma client
        run: |
          cd apps/web
          npx prisma generate

      - name: Build app
        run: |
          cd apps/web
          npm run build

      - name: Zip app for Elastic Beanstalk
        run: |
          cd apps/web
          zip -r ../web-app.zip . -x '*.git*' 'node_modules/*' 'test/*'

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: comparly-dev-app
          environment_name: comparly-dev-env
          region: eu-west-1
          version_label: ${{ github.sha }}
          deployment_package: apps/web-app.zip
